version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: TestProject123!
      MYSQL_DATABASE: meteo
      MYSQL_USER: test_user
      MYSQL_PASSWORD: TestProject123!
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: test_user
      DB_PASSWORD: TestProject123!
      DB_NAME: meteo
    command: >
      /bin/bash -c "
      uvicorn main:app --reload --host 0.0.0.0 --port 8000
      "
